







class Constants:
    # 🔹 Genesis block difficulty (4 leading zeros)

    # 🔹 Genesis block difficulty (4 leading zeros)
    GENESIS_TARGET = 0x0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF



    # 🔹 Minimum and Maximum difficulty levels
    MIN_DIFFICULTY = 0x0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    MAX_DIFFICULTY = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

    # 🔹 Difficulty adjustment parameters
    TARGET_BLOCK_TIME = 300  # 5 minutes
    DIFFICULTY_ADJUSTMENT_INTERVAL = 2  # Adjust every 2 blocks
    MIN_DIFFICULTY_FACTOR = 0.5  # Min difficulty decrease (50%)
    MAX_DIFFICULTY_FACTOR = 4.0  # Max difficulty increase (400%)

    # 🔹 Zero Hash (Used for Genesis Block and Empty Hashes)
    ZERO_HASH = "0" * 96  # SHA3-384 produces 96-character hex hashes

    MAX_SUPPLY = "84096000"
    INTIAL_COINBASE_REWARD = 100.00 
    BLOCKCHAIN_HALVING_BLOCK_HEIGHT = 420480





