







# Zyiron_Chain/blockchain/constants.py

class Constants:
    GENESIS_TARGET = 0x0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    ZERO_HASH = '0' * 96